# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_photo',
            field=models.IntegerField(default=1),
        ),
    ]
