# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_cat_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_photo',
            field=models.FileField(upload_to=''),
        ),
    ]
