# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170830_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_img',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
