# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_photo_photo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(max_length=100),
        ),
    ]
