# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170903_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_preview',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
