# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_photo_photo_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_photo_name', models.CharField(max_length=100)),
                ('top_photo_img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo_preview',
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_img',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
