# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170909_0508'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_Photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_isFavourite',
            field=models.BooleanField(default=False),
        ),
    ]
